name: vitests
on:
  push:
    branches: [main, dev, add-gh-workflow]
  pull_request:
    branches: [main]
jobs:
  yarn_lint_build_test_coverage:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn
      - name: tsc
        uses: icrawl/action-tsc@v1
        with:
          project: ./tsconfig.json
      - name: Run tests
        run: yarn test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      # - uses: romeovs/lcov-reporter-action@v0.2.16
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     lcov-file: ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}