name: vitests
on:
  push:
    branches: [main, dev, add-gh-workflow]
  pull_request:
    branches: [main]
jobs:
  yarn_lint_build_test_coverage:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn
      - name: tsc
        uses: icrawl/action-tsc@v1
        with:
          project: ./tsconfig.json
      - name: Run tests
        run: yarn test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}